version: '3.8'

services:
  web:
    build: .
    container_name: mi-web-app
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - red-interna

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: appdb
      MYSQL_USER: usuario
      MYSQL_PASSWORD: clave123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - red-interna

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: usuario
      PMA_PASSWORD: clave123
    depends_on:
      - db
    networks:
      - red-interna

volumes:
  db_data:

networks:
  red-interna:

